#spring:
#  jpa:
#    hibernate:
#      database: POSTGRESQL
#      show-sql: true                            # Show SQL statements in logs (for debugging)
#      hibernate:
#      ddl-auto: update                        # Database schema update strategy (options: none, validate, update, create, create-drop)
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres  # Database URL
#    username: postgres                        # Database username
#    password: postgres                    # Database password
#    driver-class-name: org.postgresql.Driver  # Database driver
spring:
  profiles:
    active: dev
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    enable_lazy_load_no_trans : true