apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  labels:
    app.kubernetes.io/created-by: group1-nus
    app.kubernetes.io/type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: employee-service
      app.kubernetes.io/instance: employee-service
      app.kubernetes.io/component: service
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: employee-service
        app.kubernetes.io/instance: employee-service
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: group1-nus
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-hris
      containers:
        - name: employee-service
          envFrom:
            - configMapRef:
                name: employee-service
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          image: 876708361421.dkr.ecr.ap-southeast-1.amazonaws.com/employee_service:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          resources: {}
          # requests:
          #   memory: "256Mi"
          #   cpu: "500m"
          # limits:
          #   memory: "1Gi"
          #   cpu: "1"