apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: employee-service
resources:
  - namespace.yaml
  - configMap.yaml
  - serviceAccount.yaml
  - service.yaml
  - deployment.yaml